- name: postgresql-restart
  service: >
    name={{ service_postgresql }}
    state=restarted

- name: postgresql-start
  service: >
    name={{ service_postgresql }} 
    state=started
    enabled=true

- name: postgresql-stop
  service: >
    name={{ service_postgresql }} 
    state=stopped
